image:
  file: .gitpod.Dockerfile

tasks:
  - before: |
      git config --global user.name $GITHUB_PUBLIC_NAME
      git config --global user.email $GITHUB_PUBLIC_EMAIL

  - init: |
      aws configure
