os: linux
dist: bionic
language: python

install:
- pip3 install --upgrade pip
- pip3 install molecule molecule-ec2 boto3 ansible-lint awscli junit_xml
- ansible --version
- printf '[defaults]\nroles_path=../' >ansible.cfg
script:
- "./setup.sh"
- set -e
- molecule lint
- set +e
- molecule create
- molecule converge
- ANSIBLE_STDOUT_CALLBACK=junit JUNIT_OUTPUT_DIR=reports molecule verify
- molecule destroy
- sonar-scanner
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
env:
  global:
    secure: ja8xbtp3OCWb4eQrJto0aIw/2VORoRsMLbOk9i9s2dPomsbpZ1hmLj4HB9R2dUjVk7Ke146DrNlTxiCzlODchwfOoguWFHyANudZPXehxslMZDn4Rqxg3gu3vLEvgo5u2VtANhxhjeeSvLp/SDIzU9f+KSC/bJTOEgHEvZZNaNt9/IN9u7AYhU/Mgs7JhBAMhFtmUBIU+9XjHuu2ziob++nfOawsD3N6EIBjwOzIUzgMvgW1cLu8L+c36tmZv/NVdGaBW5WMkJ5NRTE7MoAYliAnnWV0aY09eRe7kOtSoQxoPB9yNGws/4zgPkTk5T3cGVWf48VCECFpLwEXUDGCj7CJBX7ivYM4zRSnJ1njfr8Bsbmg/Ok8scV7TGknxsxVAGpUk4fYBUcGDFNpJQUC2/o0TNRMZSK8hLSPBptk61Ib7ROPVWQGtB5GmzWgFQOtvDpQkrMZdMENLfLkkXiZt6vy4zy01aj5aPngUy/t/yvVnn0SfzxzmHhnXOAtCitW5qRuyAGHiTnyaEtUtiW6ILk33Uoe2jweIPdQ4uR48nU4L/xxi8ruuzRNo007jOG1ob9JdM+dio3zW21TFOEDwUNkTu9kWZjdWu3mmPRv5Ulb8IxuVYQq9gb8cZQ161i33LZneVhw4NfpsIDPoeZXsvD7weFmv8yGlwB8N+dlxvw=
