os: linux
dist: bionic
language: python

install:
- pip3 install --upgrade pip
- pip3 install molecule molecule-ec2 boto3 ansible-lint awscli

script:
- aws configure set region $AWS_DEFAULT_REGION
- aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
- aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
- molecule test

cache:
  directories:
    - '$HOME/.cache/pip'
    - '$HOME/virtualenv'
