os: linux
dist: bionic
language: python

addons:
  sonarcloud:
    organization: "jcalavia-org"
    token: $SONAR_TOKEN  

install:
- pip3 install --upgrade pip
- pip3 install molecule molecule-ec2 boto3 ansible-lint awscli junit_xml
- ansible --version
- printf '[defaults]\nroles_path=../' >ansible.cfg
script:
- aws configure set region $AWS_DEFAULT_REGION
- aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
- aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
- molecule test
- sonar-scanner

cache:
  directories:
    - '$HOME/.cache/pip'
    - '$HOME/virtualenv'
    - '$HOME/.sonar/cache'
