os: linux
dist: bionic
language: python

addons:
  sonarcloud:
    organization: "jcalavia-org"
    token: $SONAR_TOKEN  

install:
- pip3 install --upgrade pip
- pip3 install molecule molecule-ec2 boto3 ansible-lint awscli junit_xml
- ansible --version
- printf '[defaults]\nroles_path=../' >ansible.cfg
script:
- "./setup.sh"
- set -e
- molecule lint
- set +e
- molecule create
- molecule converge
- ANSIBLE_STDOUT_CALLBACK=junit JUNIT_OUTPUT_DIR=reports molecule verify
- molecule destroy
- sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'
