os: linux
dist: bionic
language: python

addons:
  sonarcloud:
    organization: jcalavia-org
    token:
      secure: iMIbHe0+c8KVSVwEH9pA3UiBCezr8ofi6MdUKkshRmmumbbu3VG19OxdQQ2oHoAu1s5EGuQMVVD9JMLP6aivhFASZWnl7tLiiaC13WJ7iuejEEuQT6YTZAIVPnySLz1KOQuDlhpdZ05hT94lk+ueNOO7fK6IO6wdxVtwp5VritQdfA6gaCVROS1njfJM5G47wdIp49Wy559hw7HLeU//woCHo9I2l81ZcUyxzVKpkdEJucgGO9Hy6ninflb11ogJV6Def2HZte0NdVHSMW3lblIcoTppj0SLBDa1g4sfwcwiwHVxbTdiIlZlABB82GNCmBqi+C3xXNB6KkeGsTBLR0ATQNpWNFCHcIRZhs/+fVse7Inr2JUvvraAEI3iqf8wLtqMZsZpokG3odbRMtsp3A29nFhjTWsLlGmEBWyKMvi6XaC3cCvnqUj1aClOzOxFfZu9M4ePPZULzd8bgYIIhj2pKfollgiCcLI4pMh3nw6Q74AXaERmv8rsUjDAnR2xUrrwbzc8oID1mqZO2tWJdlgw9Ie3RI1+02L31TBTCHvnC7poXYXXTTMEhPSNilLGUWANqc5n/XjXef2gaQ2Uy0PARxsi4SmFay0Rj9hvi6LFmAI3FTgBMmzY2W6gjx8rlFX127fcEmQgJQkAj1g3EdXDNOZPmAlI/zrkRcDoPAc=

cache:
  directories:
  - "$HOME/.sonar/cache"
install:
- pip3 install --upgrade pip
- pip3 install molecule molecule-ec2 boto3 ansible-lint awscli junit_xml
- ansible --version
- printf '[defaults]\nroles_path=../' >ansible.cfg
script:
- ./setup.sh
- set -e
- molecule lint
- set +e
- molecule create
- molecule converge
- ANSIBLE_STDOUT_CALLBACK=junit JUNIT_OUTPUT_DIR=reports molecule verify
- molecule destroy
- sonar-scanner
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
