os: linux
dist: bionic
language: python

addons:
  sonarcloud:
    organization: "jcalavia-org"
    token: $SONAR_TOKEN  

install:
- pip3 install --upgrade pip
- pip3 install molecule molecule-ec2 boto3 ansible-lint awscli junit_xml
- ansible --version
- printf '[defaults]\nroles_path=../' >ansible.cfg
script:
- aws configure
- molecule test
- sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'
